#
# start fado server in docker container
#
services:
  fado-srv:
    image: debian:trixie
    command: "/bin/bash /var/www/html/docker/deploy-forky.sh"
    user: root
    environment:
      ROOT: "/var/www/html"
    ports:
      - 2080:2080
      - 2443:2443
#      - 80:80
#      - 443:443
    volumes:
      - /home/fa/fado:/var/www/html
#      - /home/fa/ssl:/var/www/ssl

